# Generated by Django 5.0.6 on 2025-10-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
