# Generated by Django 5.0.6 on 2025-10-16 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_release_data_video_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='videos.video'),
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
