# Generated by Django 5.0.6 on 2025-10-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_favorites_remove_video_likes_video_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='favorites',
        ),
    ]
